<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; // Import DB Facade
use App\Models\Dosen; // Pastikan Anda sudah membuat model Dosen

class DosenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dosensData = [
            [
                'nidn' => '19750810001',
                'nama_dosen' => 'Dr. Andi Wijaya, M.Kom',
                'e_mail_dosen' => 'andi.wijaya@polnep.ac.id',
                'no_telp_dosen' => '08123456701',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1975-08-10',
                'status_kepegawaian' => 'PNS',
                'bidang_keahlian' => 'Pemrograman Web',
                'deskripsi_bidang_keahlian' => 'Dr. Andi Wijaya, M.Kom memiliki keahlian utama dalam bidang pemrograman web. Beliau telah mengembangkan berbagai proyek aplikasi berbasis web, termasuk perancangan, implementasi, dan pemeliharaan sistem web. Keahlian ini mencakup penguasaan berbagai bahasa pemrograman (PHP, JavaScript), framework (Laravel, ReactJS), basis data, serta teknologi terkait yang digunakan untuk membangun situs web dan aplikasi web yang interaktif, responsif, dan aman.',
                'jenis_dosen' => 'Dosen Tetap',
                'foto_profil_dosen' => 'profil_dosen/andi_dosen.jpg',
                'tempat_tinggal_dosen' => 'Jl. Sungai Raya Dalam Komplek Cemara Indah No. 10',
                'riwayat_pendidikan' => 'S3 Ilmu Komputer',
                'perguruan_tinggi' => 'Institut Teknologi Bandung',
                'bidang_keahlian_pendidikan' => 'Pemrograman Berbasis Web',
                'minat_penelitian' => 'Desain Web : Menciptakan tampilan website yang menarik, mudah digunakan, dan sesuai dengan pengalaman pengguna. Pengembangan Web : Membangun logika, fungsionalitas, dan memastikan website berjalan dengan baik.',
                'visi_dosen' => 'Menjadi dosen yang unggul dalam menghasilkan tenaga profesional di bidang teknologi informasi yang berjiwa entrepreneur dan mampu bersaing di tingkat nasional maupun internasional.',
                'misi_dosen' => 'Menyelenggarakan pendidikan vokasi di bidang teknologi informasi yang berkualitas dan relevan dengan kebutuhan dunia industri.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nidn' => '19800101002',
                'nama_dosen' => 'Prof. Dr. Siti Aminah, M.T.',
                'e_mail_dosen' => 'siti.aminah@polnep.ac.id',
                'no_telp_dosen' => '08123456702',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1980-01-01',
                'status_kepegawaian' => 'PNS',
                'bidang_keahlian' => 'Jaringan Komputer & Keamanan Siber',
                'deskripsi_bidang_keahlian' => 'Ahli dalam arsitektur jaringan, protokol keamanan, dan kriptografi.',
                'jenis_dosen' => 'Dosen Tetap',
                'foto_profil_dosen' => 'profil_dosen/siti_dosen.jpg',
                'tempat_tinggal_dosen' => 'Jl. Pahlawan No. 2',
                'riwayat_pendidikan' => 'S3 Ilmu Komputer',
                'perguruan_tinggi' => 'Universitas Gadjah Mada',
                'bidang_keahlian_pendidikan' => 'Keamanan Jaringan',
                'minat_penelitian' => 'Keamanan IoT, Kriptografi, Forensik Digital.',
                'visi_dosen' => 'Mencetak lulusan yang kompeten di bidang keamanan siber.',
                'misi_dosen' => 'Melakukan penelitian inovatif di bidang keamanan jaringan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nidn' => '19780315003',
                'nama_dosen' => 'Dr. Budi Santoso, S.Kom., M.Kom.',
                'e_mail_dosen' => 'budi.santoso@polnep.ac.id',
                'no_telp_dosen' => '08123456703',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1978-03-15',
                'status_kepegawaian' => 'PNS',
                'bidang_keahlian' => 'Rekayasa Perangkat Lunak (RPL)',
                'deskripsi_bidang_keahlian' => 'Fokus pada metodologi pengembangan perangkat lunak, arsitektur perangkat lunak, dan pengujian perangkat lunak.',
                'jenis_dosen' => 'Dosen Tetap',
                'foto_profil_dosen' => 'profil_dosen/budi_s_dosen.jpg',
                'tempat_tinggal_dosen' => 'Jl. Kebon Jeruk No. 5',
                'riwayat_pendidikan' => 'S3 Ilmu Komputer',
                'perguruan_tinggi' => 'Universitas Indonesia',
                'bidang_keahlian_pendidikan' => 'Rekayasa Perangkat Lunak',
                'minat_penelitian' => 'Agile Development, Software Testing, Software Architecture.',
                'visi_dosen' => 'Menghasilkan insinyur perangkat lunak yang handal dan inovatif.',
                'misi_dosen' => 'Menerapkan praktik terbaik dalam pengembangan perangkat lunak.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nidn' => '19820520004',
                'nama_dosen' => 'Ir. Citra Dewi, M.Kom.',
                'e_mail_dosen' => 'citra.dewi@polnep.ac.id',
                'no_telp_dosen' => '08123456704',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1982-05-20',
                'status_kepegawaian' => 'PNS',
                'bidang_keahlian' => 'Sistem Informasi & Basis Data',
                'deskripsi_bidang_keahlian' => 'Spesialisasi dalam perancangan basis data, data mining, dan business intelligence.',
                'jenis_dosen' => 'Dosen Tetap',
                'foto_profil_dosen' => 'profil_dosen/citra_d_dosen.jpg',
                'tempat_tinggal_dosen' => 'Jl. Dago No. 20',
                'riwayat_pendidikan' => 'S2 Ilmu Komputer',
                'perguruan_tinggi' => 'Institut Teknologi Bandung',
                'bidang_keahlian_pendidikan' => 'Sistem Informasi',
                'minat_penelitian' => 'Data Mining, Business Intelligence, Big Data Analytics.',
                'visi_dosen' => 'Mencetak praktisi sistem informasi yang mampu mengelola data secara efektif.',
                'misi_dosen' => 'Mengembangkan riset di bidang sistem informasi dan basis data.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nidn' => '19850722005',
                'nama_dosen' => 'Drs. Anton Wijaya, M.T.',
                'e_mail_dosen' => 'anton.wijaya@polnep.ac.id',
                'no_telp_dosen' => '08123456705',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1985-07-22',
                'status_kepegawaian' => 'PNS',
                'bidang_keahlian' => 'Multimedia & Kreativitas Digital',
                'deskripsi_bidang_keahlian' => 'Keahlian dalam desain interaktif, aplikasi augmented/virtual reality, dan pengembangan game.',
                'jenis_dosen' => 'Dosen Tetap',
                'foto_profil_dosen' => 'profil_dosen/anton_dosen.jpg',
                'tempat_tinggal_dosen' => 'Jl. Ijen No. 15',
                'riwayat_pendidikan' => 'S2 Teknik Elektro',
                'perguruan_tinggi' => 'Universitas Brawijaya',
                'bidang_keahlian_pendidikan' => 'Multimedia Interaktif',
                'minat_penelitian' => 'Augmented Reality, Virtual Reality, Game Development.',
                'visi_dosen' => 'Mencetak kreator digital yang inovatif dan berdaya saing global.',
                'misi_dosen' => 'Mendorong penelitian di bidang multimedia dan kreativitas digital.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nidn' => '19700901006',
                'nama_dosen' => 'Prof. Dr. S. Hartono, M.Eng.',
                'e_mail_dosen' => 'hartono.s@polnep.ac.id',
                'no_telp_dosen' => '08123456706',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1970-09-01',
                'status_kepegawaian' => 'PNS',
                'bidang_keahlian' => 'Jaringan Komputer & Keamanan Siber',
                'deskripsi_bidang_keahlian' => 'Fokus pada keamanan jaringan, forensik digital, dan manajemen insiden keamanan.',
                'jenis_dosen' => 'Dosen Tetap',
                'foto_profil_dosen' => 'profil_dosen/hartono_dosen.jpg',
                'tempat_tinggal_dosen' => 'Jl. Kaliurang Km. 10',
                'riwayat_pendidikan' => 'S3 Teknik Elektro',
                'perguruan_tinggi' => 'Universitas Gadjah Mada',
                'bidang_keahlian_pendidikan' => 'Keamanan Jaringan',
                'minat_penelitian' => 'Cybersecurity, Intrusion Detection, Network Forensics.',
                'visi_dosen' => 'Menjadi pusat keunggulan dalam riset keamanan siber.',
                'misi_dosen' => 'Menghasilkan inovasi di bidang keamanan siber untuk industri.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nidn' => '19881125007',
                'nama_dosen' => 'Dr. Rina Marlina, S.Kom., M.Kom.',
                'e_mail_dosen' => 'rina.marlina@polnep.ac.id',
                'no_telp_dosen' => '08123456707',
                'tempat_lahir' => 'Pontianak',
                'tanggal_lahir' => '1988-11-25',
                'status_kepegawaian' => 'PNS',
                'bidang_keahlian' => 'Sistem Informasi & Basis Data',
                'deskripsi_bidang_keahlian' => 'Keahlian dalam pengembangan sistem informasi, basis data relasional dan non-relasional.',
                'jenis_dosen' => 'Dosen Tetap',
                'foto_profil_dosen' => 'profil_dosen/rina_dosen.jpg',
                'tempat_tinggal_dosen' => 'Jl. Ahmad Yani No. 1',
                'riwayat_pendidikan' => 'S3 Ilmu Komputer',
                'perguruan_tinggi' => 'Universitas Bina Nusantara',
                'bidang_keahlian_pendidikan' => 'Basis Data',
                'minat_penelitian' => 'Database Management Systems, Data Warehousing, Big Data.',
                'visi_dosen' => 'Mencetak generasi yang mahir dalam pengelolaan data.',
                'misi_dosen' => 'Mengembangkan sistem informasi yang efisien dan terukur.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nidn' => '19730404008',
                'nama_dosen' => 'Agus Salim, S.T., M.Eng.',
                'e_mail_dosen' => 'agus.salim@polnep.ac.id',
                'no_telp_dosen' => '08123456708',
                'tempat_lahir' => 'Pekanbaru',
                'tanggal_lahir' => '1973-04-04',
                'status_kepegawaian' => 'PNS',
                'bidang_keahlian' => 'Rekayasa Perangkat Lunak (RPL)',
                'deskripsi_bidang_keahlian' => 'Fokus pada pengembangan perangkat lunak enterprise dan arsitektur sistem.',
                'jenis_dosen' => 'Dosen Tetap',
                'foto_profil_dosen' => 'profil_dosen/agus_dosen.jpg',
                'tempat_tinggal_dosen' => 'Jl. Sukajadi No. 50',
                'riwayat_pendidikan' => 'S2 Teknik Informatika',
                'perguruan_tinggi' => 'Institut Teknologi Sepuluh Nopember',
                'bidang_keahlian_pendidikan' => 'Rekayasa Perangkat Lunak',
                'minat_penelitian' => 'Enterprise Architecture, Software Quality Assurance, Cloud Computing.',
                'visi_dosen' => 'Menghasilkan lulusan yang mampu membangun perangkat lunak berskala besar.',
                'misi_dosen' => 'Mendorong penelitian di bidang arsitektur perangkat lunak.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nidn' => '19900606009',
                'nama_dosen' => 'Endah Lestari, S.Kom., M.Kom.',
                'e_mail_dosen' => 'endah.lestari@polnep.ac.id',
                'no_telp_dosen' => '08123456709',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1990-06-06',
                'status_kepegawaian' => 'PNS',
                'bidang_keahlian' => 'Multimedia & Kreativitas Digital',
                'deskripsi_bidang_keahlian' => 'Keahlian dalam desain grafis, animasi, dan produksi konten digital.',
                'jenis_dosen' => 'Dosen Tetap',
                'foto_profil_dosen' => 'profil_dosen/endah_dosen.jpg',
                'tempat_tinggal_dosen' => 'Jl. Pandanaran No. 10',
                'riwayat_pendidikan' => 'S2 Ilmu Komputer',
                'perguruan_tinggi' => 'Universitas Diponegoro',
                'bidang_keahlian_pendidikan' => 'Desain Grafis',
                'minat_penelitian' => 'Animasi Komputer, Desain UI/UX, Virtual Reality.',
                'visi_dosen' => 'Mencetak desainer dan animator digital yang kreatif.',
                'misi_dosen' => 'Mengembangkan konten digital yang inovatif dan relevan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nidn' => '19770214010',
                'nama_dosen' => 'Dr. Rio Saputra, S.Kom., M.Eng.',
                'e_mail_dosen' => 'rio.saputra@polnep.ac.id',
                'no_telp_dosen' => '08123456710',
                'tempat_lahir' => 'Padang',
                'tanggal_lahir' => '1977-02-14',
                'status_kepegawaian' => 'PNS',
                'bidang_keahlian' => 'Jaringan Komputer & Keamanan Siber',
                'deskripsi_bidang_keahlian' => 'Fokus pada arsitektur jaringan, cloud security, dan sistem terdistribusi.',
                'jenis_dosen' => 'Dosen Tetap',
                'foto_profil_dosen' => 'profil_dosen/rio_dosen.jpg',
                'tempat_tinggal_dosen' => 'Jl. Khatib Sulaiman No. 3',
                'riwayat_pendidikan' => 'S3 Teknik Elektro',
                'perguruan_tinggi' => 'Universitas Andalas',
                'bidang_keahlian_pendidikan' => 'Cloud Computing',
                'minat_penelitian' => 'Cloud Security, Distributed Systems, Network Virtualization.',
                'visi_dosen' => 'Menjadi pemimpin dalam riset keamanan cloud.',
                'misi_dosen' => 'Mengembangkan teknologi jaringan yang aman dan efisien.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nidn' => '19830909011',
                'nama_dosen' => 'Dian Kusuma, S.Kom., M.T.',
                'e_mail_dosen' => 'dian.kusuma@polnep.ac.id',
                'no_telp_dosen' => '08123456711',
                'tempat_lahir' => 'Palangkaraya',
                'tanggal_lahir' => '1983-09-09',
                'status_kepegawaian' => 'PNS',
                'bidang_keahlian' => 'Rekayasa Perangkat Lunak (RPL)',
                'deskripsi_bidang_keahlian' => 'Keahlian dalam pengembangan aplikasi berbasis web dan mobile dengan fokus pada UI/UX.',
                'jenis_dosen' => 'Dosen Tetap',
                'foto_profil_dosen' => 'profil_dosen/dian_k_dosen.jpg',
                'tempat_tinggal_dosen' => 'Jl. Tjilik Riwut Km. 1',
                'riwayat_pendidikan' => 'S2 Teknik Informatika',
                'perguruan_tinggi' => 'Universitas Kristen Maranatha',
                'bidang_keahlian_pendidikan' => 'Pengembangan Aplikasi Mobile',
                'minat_penelitian' => 'UI/UX Design, Mobile Development, Human-Computer Interaction.',
                'visi_dosen' => 'Mencetak pengembang aplikasi yang berorientasi pengguna.',
                'misi_dosen' => 'Mendorong inovasi dalam desain dan pengembangan aplikasi.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nidn' => '19790120012',
                'nama_dosen' => 'Eko Prasetyo, S.Kom., M.Kom.',
                'e_mail_dosen' => 'eko.prasetyo@polnep.ac.id',
                'no_telp_dosen' => '08123456712',
                'tempat_lahir' => 'Pontianak',
                'tanggal_lahir' => '1979-01-20',
                'status_kepegawaian' => 'PNS',
                'bidang_keahlian' => 'Sistem Informasi & Basis Data',
                'deskripsi_bidang_keahlian' => 'Fokus pada data science, machine learning, dan analisis data besar.',
                'jenis_dosen' => 'Dosen Tetap',
                'foto_profil_dosen' => 'profil_dosen/eko_p_dosen.jpg',
                'tempat_tinggal_dosen' => 'Jl. Sultan Abdurrahman No. 7',
                'riwayat_pendidikan' => 'S2 Ilmu Komputer',
                'perguruan_tinggi' => 'Universitas Gadjah Mada',
                'bidang_keahlian_pendidikan' => 'Data Science',
                'minat_penelitian' => 'Big Data, Machine Learning, Data Analytics, Artificial Intelligence.',
                'visi_dosen' => 'Menghasilkan ahli data yang mampu mengolah informasi menjadi wawasan.',
                'misi_dosen' => 'Mengembangkan riset di bidang data science dan AI.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Memasukkan data ke dalam tabel dosens
        // Menggunakan updateOrCreate untuk menghindari duplikasi berdasarkan NIDN
        foreach ($dosensData as $data) {
            Dosen::updateOrCreate(
                ['nidn' => $data['nidn']], // Kriteria untuk mencari data yang sudah ada
                $data // Data yang akan diupdate atau dibuat
            );
        }
    }
}
