<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; // Import DB Facade
use App\Models\Mahasiswa; // Pastikan Anda sudah membuat model Mahasiswa

class MahasiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Contoh menggunakan DB Facade (jika belum ada model Mahasiswa)
        // Jika Anda sudah memiliki model Mahasiswa, lebih baik gunakan itu.

        $mahasiswasData = [
            [
                'nim' => '3202214001',
                'nama_mahasiswa' => 'Andi Wijayakusuma',
                'email_mahasiswa' => 'andi.wijaya@example.com',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Pontianak',
                'tanggal_lahir' => '2004-01-23',
                'mahasiswa_asal' => 'Singkawang',
                'tinggal_mahasiswa' => 'Jl. Sungai Raya Sukamara No. 123E',
                'agama_mahasiswa' => 'Islam',
                'no_telp_mahasiswa' => '08123456789',
                'nama_sekolah_dasar' => 'SD Negeri 1 Paloh',
                'nama_menengah_pertama' => 'SMP Negeri 3 Sambas',
                'nama_sekolah_atas' => 'MAN 3 Sambas Selatan',
                'semester' => 4,
                'ipk' => 3.82,
                'motivasi_mahasiswa' => 'Mahasiswa yang mampu dorongan diri keluarga, tujuan pribadi, dan keinginan untuk meraih kesuksesan di masa depan',
                'nama_ayah' => 'H. Muhammad Anas',
                'pekerjaan_ayah' => 'PNS (Pegawai Negeri Sipil)',
                'nama_ibu' => 'Dr. Mustika Fadillah',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'foto_profil_mhs' => 'profil_mahasiswa/andi_profil.jpg',
                'pekerjaan_bagi_mahasiswa' => 'Software Engineer di PT. Tech Innovate',
                'deskripsi_pekerjaan' => 'Seorang Software Engineer di PT. Tech Innovate akan bertanggung jawab untuk merancang, mengembangkan, menguji, dan memelihara perangkat lunak.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '3202214002',
                'nama_mahasiswa' => 'Budi Santoso',
                'email_mahasiswa' => 'budi.santoso@example.com',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2003-05-15',
                'mahasiswa_asal' => 'Jakarta',
                'tinggal_mahasiswa' => 'Jl. Merdeka No. 45',
                'agama_mahasiswa' => 'Kristen',
                'no_telp_mahasiswa' => '08121234567',
                'nama_sekolah_dasar' => 'SD Harapan',
                'nama_menengah_pertama' => 'SMP Jaya',
                'nama_sekolah_atas' => 'SMA 1 Jakarta',
                'semester' => 4,
                'ipk' => 3.75,
                'motivasi_mahasiswa' => 'Ingin menjadi ahli di bidang keamanan siber.',
                'nama_ayah' => 'Anton Wijaya',
                'pekerjaan_ayah' => 'Wiraswasta',
                'nama_ibu' => 'Siti Aminah',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'foto_profil_mhs' => 'profil_mahasiswa/budi_profil.jpg',
                'pekerjaan_bagi_mahasiswa' => null,
                'deskripsi_pekerjaan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '3202214003',
                'nama_mahasiswa' => 'Citra Dewi',
                'email_mahasiswa' => 'citra.dewi@example.com',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2004-02-20',
                'mahasiswa_asal' => 'Bandung',
                'tinggal_mahasiswa' => 'Jl. Asia Afrika No. 10',
                'agama_mahasiswa' => 'Islam',
                'no_telp_mahasiswa' => '08137654321',
                'nama_sekolah_dasar' => 'SD Pelita',
                'nama_menengah_pertama' => 'SMP Negeri 2 Bandung',
                'nama_sekolah_atas' => 'SMA 3 Bandung',
                'semester' => 4,
                'ipk' => 3.90,
                'motivasi_mahasiswa' => 'Berinovasi dalam pengembangan aplikasi mobile.',
                'nama_ayah' => 'Agus Salim',
                'pekerjaan_ayah' => 'Dosen',
                'nama_ibu' => 'Rina Marlina',
                'pekerjaan_ibu' => 'PNS',
                'foto_profil_mhs' => 'profil_mahasiswa/citra_profil.jpg',
                'pekerjaan_bagi_mahasiswa' => null,
                'deskripsi_pekerjaan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '3202214004',
                'nama_mahasiswa' => 'Dian Permata',
                'email_mahasiswa' => 'dian.permata@example.com',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '2003-11-01',
                'mahasiswa_asal' => 'Surabaya',
                'tinggal_mahasiswa' => 'Jl. Pahlawan No. 7',
                'agama_mahasiswa' => 'Buddha',
                'no_telp_mahasiswa' => '08119876543',
                'nama_sekolah_dasar' => 'SD Cemerlang',
                'nama_menengah_pertama' => 'SMP Bintang',
                'nama_sekolah_atas' => 'SMA 5 Surabaya',
                'semester' => 4,
                'ipk' => 3.68,
                'motivasi_mahasiswa' => 'Mendalami sistem informasi dan basis data.',
                'nama_ayah' => 'Joko Susanto',
                'pekerjaan_ayah' => 'Pegawai Swasta',
                'nama_ibu' => 'Maria Ulfah',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'foto_profil_mhs' => 'profil_mahasiswa/dian_profil.jpg',
                'pekerjaan_bagi_mahasiswa' => null,
                'deskripsi_pekerjaan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '3202214005',
                'nama_mahasiswa' => 'Eko Prasetyo',
                'email_mahasiswa' => 'eko.prasetyo@example.com',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '2004-07-25',
                'mahasiswa_asal' => 'Medan',
                'tinggal_mahasiswa' => 'Jl. Gatot Subroto No. 12',
                'agama_mahasiswa' => 'Katolik',
                'no_telp_mahasiswa' => '08128765432',
                'nama_sekolah_dasar' => 'SD Negeri 5 Medan',
                'nama_menengah_pertama' => 'SMP Negeri 1 Medan',
                'nama_sekolah_atas' => 'SMA Swasta Harapan',
                'semester' => 4,
                'ipk' => 3.70,
                'motivasi_mahasiswa' => 'Tertarik pada pengembangan web dan desain.',
                'nama_ayah' => 'Slamet Riyadi',
                'pekerjaan_ayah' => 'Pengusaha',
                'nama_ibu' => 'Endang Lestari',
                'pekerjaan_ibu' => 'Guru',
                'foto_profil_mhs' => 'profil_mahasiswa/eko_profil.jpg',
                'pekerjaan_bagi_mahasiswa' => null,
                'deskripsi_pekerjaan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '3202214006',
                'nama_mahasiswa' => 'Fadli Akbar',
                'email_mahasiswa' => 'fadli.akbar@example.com',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '2003-09-10',
                'mahasiswa_asal' => 'Palembang',
                'tinggal_mahasiswa' => 'Jl. Sudirman No. 88',
                'agama_mahasiswa' => 'Islam',
                'no_telp_mahasiswa' => '08136543210',
                'nama_sekolah_dasar' => 'SD Negeri 1 Palembang',
                'nama_menengah_pertama' => 'SMP Negeri 7 Palembang',
                'nama_sekolah_atas' => 'SMA Negeri 2 Palembang',
                'semester' => 4,
                'ipk' => 3.85,
                'motivasi_mahasiswa' => 'Fokus pada jaringan komputer dan keamanan siber.',
                'nama_ayah' => 'Rudi Hartono',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'Dewi Sartika',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'foto_profil_mhs' => 'profil_mahasiswa/fadli_profil.jpg',
                'pekerjaan_bagi_mahasiswa' => null,
                'deskripsi_pekerjaan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '3202214007',
                'nama_mahasiswa' => 'Gita Lestari',
                'email_mahasiswa' => 'gita.lestari@example.com',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2004-03-05',
                'mahasiswa_asal' => 'Makassar',
                'tinggal_mahasiswa' => 'Jl. Hasanuddin No. 30',
                'agama_mahasiswa' => 'Islam',
                'no_telp_mahasiswa' => '08112345678',
                'nama_sekolah_dasar' => 'SD Negeri 1 Makassar',
                'nama_menengah_pertama' => 'SMP Negeri 4 Makassar',
                'nama_sekolah_atas' => 'SMA Negeri 1 Makassar',
                'semester' => 4,
                'ipk' => 3.92,
                'motivasi_mahasiswa' => 'Menciptakan solusi teknologi yang inovatif.',
                'nama_ayah' => 'Bayu Pratama',
                'pekerjaan_ayah' => 'Dokter',
                'nama_ibu' => 'Susi Susanti',
                'pekerjaan_ibu' => 'Perawat',
                'foto_profil_mhs' => 'profil_mahasiswa/gita_profil.jpg',
                'pekerjaan_bagi_mahasiswa' => null,
                'deskripsi_pekerjaan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '3202214008',
                'nama_mahasiswa' => 'Hadi Wijaya',
                'email_mahasiswa' => 'hadi.wijaya@example.com',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '2003-10-18',
                'mahasiswa_asal' => 'Semarang',
                'tinggal_mahasiswa' => 'Jl. Pemuda No. 22',
                'agama_mahasiswa' => 'Katolik',
                'no_telp_mahasiswa' => '08129988776',
                'nama_sekolah_dasar' => 'SD Negeri 3 Semarang',
                'nama_menengah_pertama' => 'SMP Negeri 8 Semarang',
                'nama_sekolah_atas' => 'SMA Negeri 4 Semarang',
                'semester' => 4,
                'ipk' => 3.78,
                'motivasi_mahasiswa' => 'Mengembangkan sistem cerdas dan AI.',
                'nama_ayah' => 'Bambang Susilo',
                'pekerjaan_ayah' => 'Insinyur',
                'nama_ibu' => 'Sri Rahayu',
                'pekerjaan_ibu' => 'Pensiunan',
                'foto_profil_mhs' => 'profil_mahasiswa/hadi_profil.jpg',
                'pekerjaan_bagi_mahasiswa' => null,
                'deskripsi_pekerjaan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '3202214009',
                'nama_mahasiswa' => 'Intan Sari',
                'email_mahasiswa' => 'intan.sari@example.com',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2004-06-12',
                'mahasiswa_asal' => 'Yogyakarta',
                'tinggal_mahasiswa' => 'Jl. Malioboro No. 1',
                'agama_mahasiswa' => 'Islam',
                'no_telp_mahasiswa' => '08135544332',
                'nama_sekolah_dasar' => 'SD Negeri 1 Yogyakarta',
                'nama_menengah_pertama' => 'SMP Negeri 5 Yogyakarta',
                'nama_sekolah_atas' => 'SMA Negeri 7 Yogyakarta',
                'semester' => 4,
                'ipk' => 3.88,
                'motivasi_mahasiswa' => 'Berkontribusi dalam riset dan pengembangan teknologi.',
                'nama_ayah' => 'Cahyo Utomo',
                'pekerjaan_ayah' => 'Pegawai Negeri Sipil',
                'nama_ibu' => 'Dewi Anggraini',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'foto_profil_mhs' => 'profil_mahasiswa/intan_profil.jpg',
                'pekerjaan_bagi_mahasiswa' => null,
                'deskripsi_pekerjaan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '3202214010',
                'nama_mahasiswa' => 'Joko Santoso',
                'email_mahasiswa' => 'joko.santoso@example.com',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Denpasar',
                'tanggal_lahir' => '2003-08-28',
                'mahasiswa_asal' => 'Denpasar',
                'tinggal_mahasiswa' => 'Jl. Raya Kuta No. 99',
                'agama_mahasiswa' => 'Hindu',
                'no_telp_mahasiswa' => '08110987654',
                'nama_sekolah_dasar' => 'SD Negeri 2 Denpasar',
                'nama_menengah_pertama' => 'SMP Negeri 3 Denpasar',
                'nama_sekolah_atas' => 'SMA Negeri 1 Denpasar',
                'semester' => 4,
                'ipk' => 3.72,
                'motivasi_mahasiswa' => 'Menjadi pengembang game atau multimedia interaktif.',
                'nama_ayah' => 'Made Wijaya',
                'pekerjaan_ayah' => 'Seniman',
                'nama_ibu' => 'Ni Luh Putu',
                'pekerjaan_ibu' => 'Pekerja Seni',
                'foto_profil_mhs' => 'profil_mahasiswa/joko_profil.jpg',
                'pekerjaan_bagi_mahasiswa' => null,
                'deskripsi_pekerjaan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '3202214011',
                'nama_mahasiswa' => 'Kusuma Wardani',
                'email_mahasiswa' => 'kusuma.wardani@example.com',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Balikpapan',
                'tanggal_lahir' => '2004-01-01',
                'mahasiswa_asal' => 'Balikpapan',
                'tinggal_mahasiswa' => 'Jl. Jenderal Sudirman No. 5',
                'agama_mahasiswa' => 'Islam',
                'no_telp_mahasiswa' => '081277665544',
                'nama_sekolah_dasar' => 'SD Negeri 1 Balikpapan',
                'nama_menengah_pertama' => 'SMP Negeri 2 Balikpapan',
                'nama_sekolah_atas' => 'SMA Negeri 1 Balikpapan',
                'semester' => 4,
                'ipk' => 3.80,
                'motivasi_mahasiswa' => 'Tertarik pada pengembangan sistem informasi berbasis cloud.',
                'nama_ayah' => 'Supriyanto',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'Nurhayati',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'foto_profil_mhs' => 'profil_mahasiswa/kusuma_profil.jpg',
                'pekerjaan_bagi_mahasiswa' => null,
                'deskripsi_pekerjaan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '3202214012',
                'nama_mahasiswa' => 'Linda Susanti', // Perbaikan: Ini harusnya nama_mahasiswa
                'email_mahasiswa' => 'linda.susanti@example.com', // Perbaikan: Ini harusnya email_mahasiswa
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Manado',
                'tanggal_lahir' => '2003-04-20',
                'mahasiswa_asal' => 'Manado',
                'tinggal_mahasiswa' => 'Jl. Sam Ratulangi No. 100',
                'agama_mahasiswa' => 'Kristen',
                'no_telp_mahasiswa' => '081344332211',
                'nama_sekolah_dasar' => 'SD Kristen Manado',
                'nama_menengah_pertama' => 'SMP Kristen Manado',
                'nama_sekolah_atas' => 'SMA Kristen Manado',
                'semester' => 4,
                'ipk' => 3.77,
                'motivasi_mahasiswa' => 'Ingin berkontribusi dalam pengembangan aplikasi berbasis IoT.',
                'nama_ayah' => 'Daniel Hutapea',
                'pekerjaan_ayah' => 'Pendeta',
                'nama_ibu' => 'Maria Simanjuntak',
                'pekerjaan_ibu' => 'Guru',
                'foto_profil_mhs' => 'profil_mahasiswa/linda_profil.jpg',
                'pekerjaan_bagi_mahasiswa' => null,
                'deskripsi_pekerjaan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Memasukkan data ke dalam tabel mahasiswas
        // Menggunakan updateOrCreate untuk menghindari duplikasi berdasarkan NIM
        foreach ($mahasiswasData as $data) {
            Mahasiswa::updateOrCreate(
                ['nim' => $data['nim']], // Kriteria untuk mencari data yang sudah ada
                $data // Data yang akan diupdate atau dibuat
            );
        }
    }
}
